name: Fetch Angular News

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Pull latest changes from remote
        run: |
          git pull origin main

      - name: Run script
        run: node index.js

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
